---
title: "lab-06"
author: "Xingxin Li"
date: "9/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, out.width = "75%", fig.align = 'center')
```

# _Libraries_
```{r message = FALSE, warning = FALSE}
library(sf)        # vector manipulation
library(raster)    # raster manipulation
library(fasterize) # "faster" raster
library(whitebox)  # terrain analysis
library(dplyr)
library(rgdal)
library(tidyverse)
library(AOI)
library(osmdata)   # OSM API
library(elevatr)   # Elevation  Web Tiles
library(gifski)    # Gifski
```

# _Question 1 : Collecting Data_
### _1-1.2 Basin Boundary, Elevation Data_
```{r message = FALSE, warning = FALSE}
basin = read_sf("https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-11119750/basin/")
write_sf(basin, dsn = "/Users/xingxin/Github/geog176a-summer-2020-lab1/USGS-11119750.gpkg")

elev = elevatr::get_elev_raster(basin, z = 13) %>% 
  crop(basin) %>%
  mask(basin)

elev_basin = elev * 3.281

writeRaster(elev_basin, filename = "/Users/xingxin/Github/geog176a-summer-2020-lab1/mission-creek-basin-elev.tif", overwrite = TRUE)

```

### _1.3 Buildings and river-network data_
```{r message = FALSE, warning = FALSE}
elev_raster = raster("/Users/xingxin/Github/geog176a-summer-2020-lab1/mission-creek-basin-elev.tif")

bb = st_bbox(basin) %>%
  st_as_sfc() %>%
  st_transform(4326)

#Building

buildings = osmdata::opq(bb) %>% 
  add_osm_feature(key = "building") %>% 
  osmdata_sf()

#Railways

railway = opq(bb) %>% 
  add_osm_feature(key = 'railway', value = 'station' ) %>%
  osmdata_sf()

#Streams
stream = osmdata::opq(bb) %>% 
  add_osm_feature(key = 'waterway', value = "stream") %>%
  osmdata_sf() 

#buildings data

buildings_points = buildings$osm_lines %>% 
  st_intersection(basin) %>%
  st_transform(crs(basin)) 

buildings_poly = buildings$osm_polygons %>% 
  st_intersection(basin) %>%
  st_transform(crs(basin)) %>%
  st_centroid()

#railways data

railways = railway$osm_points %>% 
  st_intersection(basin) 

#streams data

streams = stream$osm_lines %>% 
  st_intersection(basin) 
```

# _Question 2 : Terrain Analysis_
### _2.1 Hillshade_
```{r message = FALSE, warning = FALSE, echo =FALSE}
wbt_hillshade("/Users/xingxin/Github/geog176a-summer-2020-lab1/mission-creek-basin-elev.tif","/Users/xingxin/Github/geog176a-summer-2020-lab1/wbt-hillside.tif")

hillshade = raster("/Users/xingxin/Github/geog176a-summer-2020-lab1/wbt-hillside.tif")

plot(hillshade, axes = FALSE, box = FALSE, col = gray.colors(256, alpha = 0.5), main = "Hillshade", legend = FALSE)
plot(streams$geometry, add = TRUE, col = "navy")
plot(basin$geometry, add = TRUE)
```


### _2.2-2.3 Height Above Nearest Drainage - River Raster, Hydrologically Corrected Surface, HAND Raster and Correcting to Local Reference Datum_
```{r message = FALSE, warning = FALSE, echo =FALSE}
river_raster = streams %>%
  st_transform(5070) %>%
  st_buffer(10) %>%
  st_transform(crs(elev_raster))

stream_raster = fasterize::fasterize(river_raster, elev_basin)

writeRaster(stream_raster, filename = "/Users/xingxin/Github/geog176a-summer-2020-lab1/river-raster.tif", overwrite = TRUE)
```


```{r message = FALSE, warning = FALSE, echo =FALSE}
streams_raster = raster("/Users/xingxin/Github/geog176a-summer-2020-lab1/river-raster.tif")

wbt_breach_depressions("/Users/xingxin/Github/geog176a-summer-2020-lab1/mission-creek-basin-elev.tif","/Users/xingxin/Github/geog176a-summer-2020-lab1/hydro-corr-surf-elev.tif")

wbt_elevation_above_stream("/Users/xingxin/Github/geog176a-summer-2020-lab1/hydro-corr-surf-elev.tif","/Users/xingxin/Github/geog176a-summer-2020-lab1/river-raster.tif", "/Users/xingxin/Github/geog176a-summer-2020-lab1/wbt_elevation_above_stream.tif")

```


```{r message = FALSE, warning = FALSE, echo =FALSE}
HAND = raster("/Users/xingxin/Github/geog176a-summer-2020-lab1/wbt_elevation_above_stream.tif")

HAND_raster = HAND + 3.69

streams_raster = raster("/Users/xingxin/Github/geog176a-summer-2020-lab1/river-raster.tif")

HAND_raster[streams_raster == 1] = 0

writeRaster(HAND_raster, filename = "/Users/xingxin/Github/geog176a-summer-2020-lab1/hand-raster.tif", overwrite = TRUE)

```


# _Question 3: 2017 Impact Assessmen_
### _3.1 Map of the Flood_
```{r message = FALSE, warning = FALSE}

Floods = raster("/Users/xingxin/Github/geog176a-summer-2020-lab1/hand-raster.tif")

Flood_offset = Floods

Flood_offset[Flood_offset > 10.02] = NA

```

### _3.2-1 Plots_
```{r message = FALSE, warning = FALSE}
plot(hillshade, axes = FALSE, box = FALSE, col= gray.colors(256, alpha = .5), legend=FALSE)

plot(Flood_offset, add=TRUE, col= rev(blues9), legend=FALSE)

plot(railways$geometry, add=TRUE, col= "green", cex=1, pch=16)
```


### _Final plots_
```{r message = FALSE, warning = FALSE}
cols = ifelse(!is.na(raster::extract(Flood_offset, buildings_poly)), "red", "black")

stage = 10.02

plot(hillshade, axes = FALSE, box = FALSE, col = gray.colors(256, alpha = 0.5), legend = FALSE, main = paste(sum(cols =="red"), "impacted building",stage, "foot stage"), cex = 0.5)

plot(Flood_offset, add = TRUE, col = rev(blues9))

plot(buildings_poly, add = TRUE, col = cols, cex =  .08, pch = 16)

plot(railways, add = TRUE, col = "green", cex = 1, pch = 16)

```

```{r message = FALSE, warning = FALSE}
#Extra Credits



```
